// /errors/firebaseErrors.js
export const firebaseErrorMessages = {
    // ------ Errores Auth -------
    "auth/claims-too-large": "⚠️ Los datos personalizados para el usuario son demasiado grandes.",
    "auth/email-already-exists": "📧 Este correo electrónico ya está registrado.",
    "auth/id-token-expired": "🔒 Tu sesión ha expirado, inicia sesión de nuevo.",
    "auth/id-token-revoked": "🔒 La sesión fue revocada, inicia sesión de nuevo.",
    "auth/insufficient-permission": "🚫 No tienes permisos suficientes para realizar esta acción.",
    "auth/internal-error": "😱 Ocurrió un error interno. Intenta de nuevo o contacta soporte.",
    "auth/invalid-argument": "⚠️ Se proporcionó un dato no válido.",
    "auth/invalid-claims": "⚠️ Los datos personalizados del usuario no son válidos.",
    "auth/invalid-continue-uri": "🔗 La URL de redirección no es válida.",
    "auth/invalid-creation-time": "⏰ El dato de creación de usuario no es válido.",
    "auth/invalid-credential": "🔑 La credenciales de autenticación no son válidas.",
    "auth/invalid-disabled-field": "⚠️ El valor de 'deshabilitado' debe ser verdadero o falso.",
    "auth/invalid-display-name": "📝 El nombre de usuario no es válido.",
    "auth/invalid-dynamic-link-domain": "🔗 El dominio del link dinámico no está autorizado para este proyecto.",
    "auth/invalid-email": "📧 El correo electrónico no es válido.",
    "auth/invalid-email-verified": "⚠️ El valor de verificación de email no es válido.",
    "auth/invalid-hash-algorithm": "⚙️ El algoritmo de hash no es válido.",
    "auth/invalid-hash-block-size": "📏 El tamaño del bloque de hash no es válido.",
    "auth/invalid-hash-derived-key-length": "📏 La longitud de la clave de hash no es válida.",
    "auth/invalid-hash-key": "🔑 La clave de hash no es válida.",
    "auth/invalid-hash-memory-cost": "💾 El costo de memoria de hash no es válido.",
    "auth/invalid-hash-parallelization": "⚙️ El parámetro de paralelización de hash no es válido.",
    "auth/invalid-hash-rounds": "🔄 El número de rondas de hash no es válido.",
    "auth/invalid-hash-salt-separator": "⚠️ El separador de sal de hash no es válido.",
    "auth/invalid-id-token": "🔒 El token de sesión no es válido.",
    "auth/invalid-last-sign-in-time": "⏰ El dato del último acceso no es válido.",
    "auth/invalid-page-token": "🔄 El token de página no es válido.",
    "auth/invalid-password": "🔑 La contraseña debe tener al menos 6 caracteres.",
    "auth/invalid-password-hash": "⚠️ El hash de contraseña no es válido.",
    "auth/invalid-password-salt": "⚠️ El dato de sal de contraseña no es válido.",
    "auth/invalid-phone-number": "📱 El número de teléfono no es válido.",
    "auth/invalid-photo-url": "🖼️ La URL de la foto de perfil no es válida.",
    "auth/invalid-provider-data": "⚠️ Los datos del proveedor de autenticación no son válidos.",
    "auth/invalid-provider-id": "⚠️ El identificador del proveedor no es válido.",
    "auth/invalid-oauth-responsetype": "⚠️ La configuración de OAuth no es válida.",
    "auth/invalid-session-cookie-duration": "⏳ La duración de la sesión debe ser entre 5 minutos y 2 semanas.",
    "auth/invalid-uid": "🆔 El identificador de usuario no es válido.",
    "auth/invalid-user-import": "⚠️ Los datos de usuario para importar no son válidos.",
    "auth/maximum-user-count-exceeded": "🚫 Se excedió la cantidad máxima de usuarios permitidos para importar.",
    "auth/missing-android-pkg-name": "📱 Falta el nombre del paquete de Android.",
    "auth/missing-continue-uri": "🔗 Falta la URL de redirección.",
    "auth/missing-hash-algorithm": "⚙️ Falta el algoritmo de hash para importar contraseñas.",
    "auth/missing-ios-bundle-id": "📱 Falta el ID de bundle de iOS.",
    "auth/missing-uid": "🆔 Falta el identificador de usuario.",
    "auth/missing-oauth-client-secret": "🔒 Falta el secreto de cliente OAuth.",
    "auth/operation-not-allowed": "🚫 Este método de autenticación está deshabilitado.",
    "auth/phone-number-already-exists": "📱 Este número de teléfono ya está registrado.",
    "auth/project-not-found": "🚫 No se encontró el proyecto de Firebase.",
    "auth/reserved-claims": "⚠️ Se usaron atributos reservados en los datos personalizados.",
    "auth/session-cookie-expired": "⏳ La sesión ha expirado.",
    "auth/session-cookie-revoked": "⏳ La sesión fue revocada.",
    "auth/too-many-requests": "🚫 Demasiados intentos. Intenta más tarde.",
    "auth/uid-already-exists": "🆔 El identificador de usuario ya existe.",
    "auth/unauthorized-continue-uri": "🔗 La URL de redirección no está permitida.",
    "auth/user-not-found": "🔍 No existe ningún usuario con esos datos.",
    // ------ Otros comunes ------
    "auth/email-already-in-use": "📧 Este correo ya está registrado.",
    "auth/wrong-password": "🔑 La contraseña es incorrecta.",
    "auth/user-disabled": "🚫 La cuenta está deshabilitada.",
    // ------ Generales ---------
    "permission-denied": "🚫 No tienes permisos para realizar esta acción.",
    "unavailable": "⏳ El servicio no está disponible. Intenta más tarde.",
    "not-found": "🔍 No se encontró el documento solicitado.",
    "default": "❌ Ocurrió un error inesperado. Intenta de nuevo.",
};